@echo off
EvolutionUnpack B.AnimRetarget.cache
EvolutionUnpack B.CharacterCodesCache.cache
EvolutionUnpack B.CharacterCodesCacheDx10.cache
EvolutionUnpack B.CharacterCodesCacheDx11.cache
EvolutionUnpack B.CharacterCodesCacheDx9.cache
EvolutionUnpack B.Font.cache
EvolutionUnpack B.Misc.cache
EvolutionUnpack B.ShaderDx10.cache
EvolutionUnpack B.ShaderDx11.cache
EvolutionUnpack B.ShaderDx9.cache
EvolutionUnpack B.ShaderPermutationDx10.cache
EvolutionUnpack B.ShaderPermutationDx11.cache
EvolutionUnpack B.ShaderPermutationDx9.cache
EvolutionUnpack B.TextureDx9.cache
EvolutionUnpack F.Misc.cache
EvolutionUnpack F.TextureDx9.cache
EvolutionUnpack H.AnimRetarget.cache
EvolutionUnpack H.CharacterCodesCache.cache
EvolutionUnpack H.CharacterCodesCacheDx10.cache
EvolutionUnpack H.CharacterCodesCacheDx11.cache
EvolutionUnpack H.CharacterCodesCacheDx9.cache
EvolutionUnpack H.Font.cache
EvolutionUnpack H.Misc.cache
EvolutionUnpack H.ShaderDx10.cache
EvolutionUnpack H.ShaderDx11.cache
EvolutionUnpack H.ShaderDx9.cache
EvolutionUnpack H.ShaderPermutationDx10.cache
EvolutionUnpack H.ShaderPermutationDx11.cache
EvolutionUnpack H.ShaderPermutationDx9.cache
echo Complete
@pause
